"""Generate SearchPresetCatalog.Extended.cs and BlacklistPresetCatalog.Extended.cs"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "Rule34GalleryApp" / "Services"

BASE_SEARCH_IDS = {
    "solo_female", "solo_male", "lesbian", "hetero", "threesome_ffm", "group",
    "animated", "gif", "video", "comic", "3d", "highres", "english", "cosplay",
    "huge_breasts", "flat_chest", "tentacles", "outdoors", "monster_girl",
    "pokemon", "genshin", "overwatch", "marvel", "nintendo", "zelda", "league",
    "fortnite", "minecraft", "disney", "star_wars", "harry_potter", "hololive",
    "fate", "touhou", "kantai", "azur_lane", "fire_emblem", "street_fighter",
    "tekken", "final_fantasy", "resident_evil", "sonic", "undertale", "bikini",
    "school_uniform", "maid", "nurse", "catgirl", "foxgirl", "demon_girl", "elf",
    "thighhighs", "glasses", "dark_skin", "muscular_female", "blowjob", "paizuri",
    "anal", "kiss", "uncensored", "western_art", "pixel_art", "sketch", "mmf", "fff",
}

BASE_BLACKLIST_IDS = {
    "furry", "ai", "futa", "male", "hyper", "scat", "gore", "vore", "incest", "tf",
    "feet", "pregnant", "loli_shota", "noncon", "bestiality", "tentacles", "bondage",
    "femboy", "inflation", "macro_micro", "bbw", "monster", "mind_control", "ntr",
    "latex", "furry_cub", "watersports", "diaper", "skinsuit", "amputee", "insect",
    "loli_shota_extra", "necro", "cannibalism", "tickling", "armpit", "fart", "smell",
    "drugs", "smoking", "slavery", "pegging", "femdom", "maledom", "cuckold", "slime",
    "robot", "furry_avian", "hyper_pregnancy", "lactation", "urine_drinking",
    "public_use", "bestiality_alt", "guro_extreme", "parasite", "body_writing",
    "humiliation", "yuri_exclude", "bara_exclude",
}


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def fmt_tags(tags: list[str]) -> str:
    inner = ", ".join(f'"{esc(t)}"' for t in tags)
    return f"[{inner}]"


def emit_preset(id_: str, name: str, desc: str, tags: list[str]) -> list[str]:
    return [
        "        new()",
        "        {",
        f'            Id = "{esc(id_)}",',
        f'            Name = "{esc(name)}",',
        f'            Description = "{esc(desc)}",',
        f"            Tags = {fmt_tags(tags)},",
        "        },",
    ]


def write_file(path: Path, class_name: str, preset_type: str, presets: list[tuple]):
    lines = [
        "namespace Rule34GalleryApp.Services;",
        "",
        f"public static partial class {class_name}",
        "{",
        f"    private static readonly {preset_type}[] ExtendedPresets =",
        "    [",
    ]
    for id_, name, desc, tags in presets:
        lines.extend(emit_preset(id_, name, desc, tags))
    lines.append("    ];")
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def add_unique(presets: list, seen: set, id_: str, name: str, desc: str, tags: list[str]):
    if id_ in seen:
        return
    seen.add(id_)
    presets.append((id_, name, desc, tags))


def build_search() -> list:
    presets: list = []
    seen = set(BASE_SEARCH_IDS)

    franchises = [
        ("one_piece", "One Piece", "Pirates adventure", ["one_piece"]),
        ("naruto", "Naruto", "Ninja world", ["naruto"]),
        ("bleach", "Bleach", "Soul reapers", ["bleach"]),
        ("dragon_ball", "Dragon Ball", "Martial arts", ["dragon_ball"]),
        ("jojo", "JoJo's Bizarre Adventure", "Bizarre adventures", ["jojo's_bizarre_adventure"]),
        ("mha", "My Hero Academia", "Hero academy", ["boku_no_hero_academia"]),
        ("demon_slayer", "Demon Slayer", "Kimetsu no Yaiba", ["kimetsu_no_yaiba"]),
        ("jjk", "Jujutsu Kaisen", "Cursed spirits", ["jujutsu_kaisen"]),
        ("chainsaw_man", "Chainsaw Man", "Devils and chainsaws", ["chainsaw_man"]),
        ("spy_x_family", "Spy x Family", "Spy family", ["spy_x_family"]),
        ("evangelion", "Evangelion", "Mecha drama", ["neon_genesis_evangelion"]),
        ("sailor_moon", "Sailor Moon", "Magical girls", ["sailor_moon"]),
        ("madoka", "Madoka Magica", "Magical girls", ["mahou_shoujo_madoka_magica"]),
        ("love_live", "Love Live", "Idol school", ["love_live"]),
        ("idolmaster", "The Idolmaster", "Idol franchise", ["idolmaster"]),
        ("blue_archive", "Blue Archive", "Schale students", ["blue_archive"]),
        ("honkai_star_rail", "Honkai: Star Rail", "Trailblazers", ["honkai:_star_rail"]),
        ("honkai_impact", "Honkai Impact", "Honkai battles", ["honkai_impact_3rd"]),
        ("arknights", "Arknights", "Rhodes Island", ["arknights"]),
        ("persona_5", "Persona 5", "Phantom thieves", ["persona_5"]),
        ("persona_4", "Persona 4", "Investigation team", ["persona_4"]),
        ("nier", "NieR", "YoRHa and androids", ["nier_(series)"]),
        ("bayonetta", "Bayonetta", "Umbra witch", ["bayonetta"]),
        ("metroid", "Metroid", "Samus adventures", ["metroid"]),
        ("kirby", "Kirby", "Dream Land", ["kirby_(series)"]),
        ("splatoon", "Splatoon", "Ink battles", ["splatoon_(series)"]),
        ("xenoblade", "Xenoblade", "Chronicles", ["xenoblade_chronicles_(series)"]),
        ("animal_crossing", "Animal Crossing", "Village life", ["animal_crossing"]),
        ("digimon", "Digimon", "Digital monsters", ["digimon"]),
        ("rezero", "Re:Zero", "Isekai loop", ["re:zero"]),
        ("konosuba", "Konosuba", "Fantasy comedy", ["kono_subarashii_sekai_ni_shukufuku_wo!"]),
        ("overlord_anime", "Overlord", "Nazarick", ["overlord_(maruyama)"]),
        ("highschool_dxd", "High School DxD", "Devils and angels", ["highschool_dxd"]),
        ("date_a_live", "Date A Live", "Spirits", ["date_a_live"]),
        ("tolove_ru", "To Love-Ru", "Alien harem", ["to_love-ru"]),
        ("steins_gate", "Steins;Gate", "Time travel", ["steins;gate"]),
        ("monogatari", "Monogatari", "Oddities", ["monogatari_(series)"]),
        ("oshi_no_ko", "Oshi no Ko", "Idol drama", ["oshi_no_ko"]),
        ("frieren", "Frieren", "After the journey", ["sousou_no_frieren"]),
        ("dungeon_meshi", "Dungeon Meshi", "Dungeon dining", ["dungeon_meshi"]),
        ("mob_psycho", "Mob Psycho 100", "Psychic powers", ["mob_psycho_100"]),
        ("opm", "One Punch Man", "Hero association", ["one-punch_man"]),
        ("hxh", "Hunter x Hunter", "Hunters", ["hunter_x_hunter"]),
        ("black_clover", "Black Clover", "Magic knights", ["black_clover"]),
        ("fairy_tail", "Fairy Tail", "Guild mages", ["fairy_tail"]),
        ("rwby", "RWBY", "Huntresses", ["rwby"]),
        ("precure", "Precure", "Magical warriors", ["precure"]),
        ("gundam", "Gundam", "Mecha wars", ["gundam"]),
        ("fullmetal_alchemist", "Fullmetal Alchemist", "Alchemy", ["fullmetal_alchemist"]),
        ("code_geass", "Code Geass", "Geass", ["code_geass"]),
        ("vocaloid", "Vocaloid", "Virtual singers", ["vocaloid"]),
        ("uma_musume", "Uma Musume", "Horse girls", ["umamusume"]),
        ("project_sekai", "Project Sekai", "Rhythm idols", ["project_sekai"]),
        ("bang_dream", "BanG Dream", "Band girls", ["bang_dream!"]),
        ("granblue", "Granblue Fantasy", "Sky journey", ["granblue_fantasy"]),
        ("kingdom_hearts", "Kingdom Hearts", "Keyblade", ["kingdom_hearts"]),
        ("senran_kagura", "Senran Kagura", "Shinobi", ["senran_kagura"]),
        ("dead_or_alive", "Dead or Alive", "Fighters", ["dead_or_alive"]),
        ("soul_calibur", "Soulcalibur", "Weapons", ["soulcalibur"]),
        ("king_of_fighters", "King of Fighters", "SNK fighters", ["the_king_of_fighters"]),
        ("mortal_kombat", "Mortal Kombat", "Kombat", ["mortal_kombat"]),
        ("guilty_gear", "Guilty Gear", "Rock music fighters", ["guilty_gear"]),
        ("blazblue", "BlazBlue", "Azure", ["blazblue"]),
        ("skullgirls", "Skullgirls", "New Meridian", ["skullgirls"]),
        ("dragon_quest", "Dragon Quest", "Slime heroes", ["dragon_quest"]),
        ("ff7", "Final Fantasy VII", "Midgar", ["final_fantasy_vii"]),
        ("ff14", "Final Fantasy XIV", "Eorzea", ["final_fantasy_xiv"]),
        ("yakuza", "Yakuza", "Kamurocho", ["yakuza"]),
        ("danganronpa", "Danganronpa", "Hope and despair", ["danganronpa_(series)"]),
        ("kill_la_kill", "Kill la Kill", "Life fibers", ["kill_la_kill"]),
        ("gurren_lagann", "Gurren Lagann", "Drill", ["tengen_toppa_gurren-lagann"]),
        ("gravity_falls", "Gravity Falls", "Mystery shack", ["gravity_falls"]),
        ("avatar_tla", "Avatar: The Last Airbender", "Bending", ["avatar:_the_last_airbender"]),
        ("ben_10", "Ben 10", "Omnitrix", ["ben_10"]),
        ("totally_spies", "Totally Spies", "Spies", ["totally_spies"]),
        ("adventure_time", "Adventure Time", "Land of Ooo", ["adventure_time"]),
        ("steven_universe", "Steven Universe", "Gems", ["steven_universe"]),
        ("mlp", "My Little Pony", "Friendship", ["my_little_pony"]),
        ("warcraft", "Warcraft", "Azeroth", ["warcraft"]),
        ("wow", "World of Warcraft", "MMO fantasy", ["world_of_warcraft"]),
        ("diablo", "Diablo", "Sanctuary", ["diablo_(series)"]),
        ("elder_scrolls", "The Elder Scrolls", "Tamriel", ["the_elder_scrolls"]),
        ("skyrim", "Skyrim", "Dragonborn", ["the_elder_scrolls_v:_skyrim"]),
        ("fallout", "Fallout", "Wasteland", ["fallout_(series)"]),
        ("mass_effect", "Mass Effect", "Galaxy", ["mass_effect_(series)"]),
        ("halo", "Halo", "Spartans", ["halo_(series)"]),
        ("apex_legends", "Apex Legends", "Battle royale", ["apex_legends"]),
        ("valorant", "Valorant", "Agents", ["valorant"]),
        ("half_life", "Half-Life", "Combine", ["half-life_(series)"]),
        ("portal", "Portal", "Aperture", ["portal_(series)"]),
        ("bioshock", "BioShock", "Rapture", ["bioshock_(series)"]),
        ("assassins_creed", "Assassin's Creed", "Assassins", ["assassin's_creed_(series)"]),
        ("god_of_war", "God of War", "Norse myth", ["god_of_war"]),
        ("cyberpunk_2077", "Cyberpunk 2077", "Night City", ["cyberpunk_2077"]),
        ("witcher", "The Witcher", "Monster hunter", ["the_witcher_(series)"]),
        ("elden_ring", "Elden Ring", "Lands Between", ["elden_ring"]),
        ("dark_souls", "Dark Souls", "Soulslike", ["dark_souls_(series)"]),
        ("bloodborne", "Bloodborne", "Yharnam", ["bloodborne"]),
        ("sekiro", "Sekiro", "Shinobi", ["sekiro:_shadows_die_twice"]),
        ("monster_hunter", "Monster Hunter", "Hunts", ["monster_hunter_(series)"]),
        ("devil_may_cry", "Devil May Cry", "Demons", ["devil_may_cry_(series)"]),
        ("castlevania", "Castlevania", "Vampires", ["castlevania_(series)"]),
        ("hollow_knight", "Hollow Knight", "Hallownest", ["hollow_knight"]),
        ("deltarune", "Deltarune", "Dark world", ["deltarune"]),
        ("cuphead", "Cuphead", "Inkwell", ["cuphead_(game)"]),
        ("fnaf", "Five Nights at Freddy's", "Animatronics", ["five_nights_at_freddy's"]),
        ("terraria", "Terraria", "Sandbox", ["terraria"]),
        ("stardew_valley", "Stardew Valley", "Farm life", ["stardew_valley"]),
        ("roblox", "Roblox", "Platform", ["roblox"]),
        ("among_us", "Among Us", "Crewmates", ["among_us"]),
        ("plants_vs_zombies", "Plants vs. Zombies", "Tower defense", ["plants_vs._zombies"]),
        ("dc_comics", "DC Comics", "DC heroes", ["dc_comics"]),
        ("batman", "Batman", "Gotham", ["batman_(series)"]),
        ("superman", "Superman", "Kryptonian", ["superman_(series)"]),
        ("spider_man", "Spider-Man", "Web-slinger", ["spider-man_(series)"]),
        ("x_men", "X-Men", "Mutants", ["x-men"]),
        ("invincible", "Invincible", "Image hero", ["invincible_(series)"]),
        ("helluva_boss", "Helluva Boss", "Imp company", ["helluva_boss"]),
        ("hazbin_hotel", "Hazbin Hotel", "Redemption hotel", ["hazbin_hotel"]),
        ("arcane", "Arcane", "League show", ["arcane:_league_of_legends"]),
        ("the_last_of_us", "The Last of Us", "Survival", ["the_last_of_us"]),
        ("bioshock_elizabeth", "BioShock Infinite", "Columbia", ["bioshock_infinite"]),
        ("nier_automata", "NieR: Automata", "YoRHa", ["nier:_automata"]),
        ("nier_replicant", "NieR Replicant", "Replicant", ["nier_replicant"]),
        ("dragon_age", "Dragon Age", "Thedas", ["dragon_age_(series)"]),
        ("mass_effect_liara", "Mass Effect Liara", "Asari", ["mass_effect_(series)", "liara_t'soni"]),
        ("borderlands", "Borderlands", "Vault hunters", ["borderlands_(series)"]),
        ("doom", "DOOM", "Slayer", ["doom_(series)"]),
        ("metroid_samus", "Samus Aran", "Bounty hunter", ["metroid", "samus_aran"]),
        ("zelda_link", "Link", "Hero of Hyrule", ["the_legend_of_zelda", "link"]),
        ("mario", "Super Mario", "Mushroom Kingdom", ["super_mario_bros."]),
        ("pokemon_trainer", "Pokémon trainer", "Trainer art", ["pokemon", "pokemon_trainer"]),
        ("genshin_traveler", "Genshin Traveler", "Traveler", ["genshin_impact", "traveler_(genshin_impact)"]),
    ]
    for id_, name, desc, tags in franchises:
        add_unique(presets, seen, id_, name, desc, tags)

    acts = [
        ("cowgirl", "Cowgirl", "Riding position", ["cowgirl_position"]),
        ("doggystyle", "Doggystyle", "From behind", ["doggystyle"]),
        ("missionary", "Missionary", "Face to face", ["missionary"]),
        ("reverse_cowgirl", "Reverse cowgirl", "Facing away", ["reverse_cowgirl"]),
        ("mating_press", "Mating press", "Pinned", ["mating_press"]),
        ("full_nelson", "Full nelson", "Held position", ["full_nelson"]),
        ("sixty_nine", "69", "Mutual oral", ["69"]),
        ("handjob", "Handjob", "Manual", ["handjob"]),
        ("footjob", "Footjob", "Feet", ["footjob"]),
        ("cunnilingus", "Cunnilingus", "Oral on female", ["cunnilingus"]),
        ("facesitting", "Facesitting", "Sitting on face", ["facesitting"]),
        ("deepthroat", "Deepthroat", "Oral depth", ["deepthroat"]),
        ("female_masturbation", "Female masturbation", "Solo play", ["female_masturbation"]),
        ("male_masturbation", "Male masturbation", "Solo play", ["male_masturbation"]),
        ("dildo", "Dildo", "Toy", ["dildo"]),
        ("vibrator", "Vibrator", "Toy", ["vibrator"]),
        ("creampie", "Creampie", "Internal finish", ["creampie"]),
        ("facial", "Facial", "Face finish", ["facial"]),
        ("cum_on_body", "Cum on body", "Body finish", ["cum_on_body"]),
        ("bukkake", "Bukkake", "Multiple finish", ["bukkake"]),
        ("gangbang", "Gangbang", "Many partners", ["gangbang"]),
        ("double_penetration", "Double penetration", "DP", ["double_penetration"]),
        ("spitroast", "Spitroast", "Two on one", ["spitroast"]),
        ("public_sex", "Public sex", "In public", ["public", "sex"]),
        ("outdoor_sex", "Outdoor sex", "Outside", ["outdoors", "sex"]),
        ("shower_sex", "Shower sex", "In shower", ["shower", "sex"]),
        ("onsen", "Onsen", "Hot spring", ["onsen"]),
        ("classroom", "Classroom", "School setting", ["classroom"]),
        ("office_lady", "Office lady", "OL", ["office_lady"]),
        ("bunny_girl", "Bunny girl", "Playboy bunny", ["bunny_girl"]),
        ("angel", "Angel", "Angel character", ["angel"]),
        ("witch", "Witch", "Witch character", ["witch"]),
        ("nun", "Nun", "Nun outfit", ["nun"]),
        ("police", "Police", "Officer", ["policewoman"]),
        ("military_uniform", "Military", "Uniform", ["military"]),
        ("kimono", "Kimono", "Traditional", ["kimono"]),
        ("china_dress", "China dress", "Cheongsam", ["china_dress"]),
        ("wedding_dress", "Wedding dress", "Bridal", ["wedding_dress"]),
        ("lingerie", "Lingerie", "Underwear", ["lingerie"]),
        ("panties", "Panties", "Underwear", ["panties"]),
        ("bra", "Bra", "Underwear", ["bra"]),
        ("skirt_lift", "Skirt lift", "Lifted skirt", ["skirt_lift"]),
        ("shirt_lift", "Shirt lift", "Lifted shirt", ["shirt_lift"]),
        ("undressing", "Undressing", "Stripping", ["undressing"]),
        ("nude", "Nude", "Fully nude", ["nude"]),
        ("partially_clothed", "Partially clothed", "Some clothes", ["partially_clothed"]),
        ("garter_belt", "Garter belt", "Lingerie", ["garter_belt"]),
        ("high_heels", "High heels", "Heels", ["high_heels"]),
        ("blonde_hair", "Blonde hair", "Hair color", ["blonde_hair"]),
        ("brown_hair", "Brown hair", "Hair color", ["brown_hair"]),
        ("red_hair", "Red hair", "Hair color", ["red_hair"]),
        ("blue_hair", "Blue hair", "Hair color", ["blue_hair"]),
        ("pink_hair", "Pink hair", "Hair color", ["pink_hair"]),
        ("white_hair", "White hair", "Hair color", ["white_hair"]),
        ("long_hair", "Long hair", "Hair length", ["long_hair"]),
        ("short_hair", "Short hair", "Hair length", ["short_hair"]),
        ("twintails", "Twintails", "Hairstyle", ["twintails"]),
        ("ponytail", "Ponytail", "Hairstyle", ["ponytail"]),
        ("braid", "Braid", "Hairstyle", ["braid"]),
        ("large_breasts", "Large breasts", "Big chest", ["large_breasts"]),
        ("medium_breasts", "Medium breasts", "Mid chest", ["medium_breasts"]),
        ("small_breasts", "Small breasts", "Small chest", ["small_breasts"]),
        ("wide_hips", "Wide hips", "Curvy hips", ["wide_hips"]),
        ("thick_thighs", "Thick thighs", "Thicc", ["thick_thighs"]),
        ("plump", "Plump", "Soft body", ["plump"]),
        ("petite", "Petite", "Small frame", ["petite"]),
        ("mature_female", "Mature female", "Older woman", ["mature_female"]),
        ("milf", "MILF", "Mature", ["milf"]),
        ("shortstack", "Shortstack", "Short adult", ["shortstack"]),
        ("tall_female", "Tall female", "Tall", ["tall_female"]),
        ("toned", "Toned body", "Fit", ["toned"]),
        ("sweat", "Sweaty", "Sweat", ["sweat"]),
        ("wet", "Wet", "Wet body", ["wet"]),
        ("oiled", "Oiled", "Oil shine", ["oiled"]),
        ("tan", "Tan", "Tanned skin", ["tan"]),
        ("freckles", "Freckles", "Face freckles", ["freckles"]),
        ("tattoo", "Tattoo", "Body ink", ["tattoo"]),
        ("piercing", "Piercing", "Body piercing", ["piercing"]),
        ("looking_at_viewer", "Looking at viewer", "Eye contact", ["looking_at_viewer"]),
        ("smile", "Smiling", "Happy", ["smile"]),
        ("blush", "Blush", "Embarrassed", ["blush"]),
        ("ahegao", "Ahegao", "Face", ["ahegao"]),
        ("femdom_search", "Femdom", "Female dom", ["femdom"]),
        ("bondage_search", "Bondage", "Tied up", ["bondage"]),
        ("bdsm_search", "BDSM", "Kink", ["bdsm"]),
        ("frottage", "Frottage", "Grinding", ["frottage"]),
        ("tribadism", "Tribadism", "Girl grinding", ["tribadism"]),
        ("fingering", "Fingering", "Manual", ["fingering"]),
        ("squirting", "Squirting", "Squirt", ["squirting"]),
        ("orgasm", "Orgasm", "Climax", ["orgasm"]),
        ("after_sex", "After sex", "Post", ["after_sex"]),
        ("before_sex", "Before sex", "Pre", ["before_sex"]),
        ("clothed_sex", "Clothed sex", "With clothes", ["clothed_sex"]),
        ("imminent_sex", "Imminent sex", "About to", ["imminent_sex"]),
        ("under_table", "Under table", "Hidden", ["under_table"]),
        ("library", "Library", "Quiet place", ["library"]),
        ("car_interior", "Car sex", "Vehicle", ["car_interior"]),
        ("train_interior", "Train", "Transit", ["train_interior"]),
        ("locker_room", "Locker room", "Changing", ["locker_room"]),
        ("gym", "Gym", "Workout", ["gym"]),
        ("pool", "Pool", "Swimming", ["pool"]),
        ("beach", "Beach", "Sand and sea", ["beach"]),
        ("forest", "Forest", "Woods", ["forest"]),
        ("night", "Night", "Dark sky", ["night"]),
        ("moonlight", "Moonlight", "Night light", ["moonlight"]),
        ("rain", "Rain", "Wet weather", ["rain"]),
        ("snow", "Snow", "Winter", ["snow"]),
        ("christmas", "Christmas", "Holiday", ["christmas"]),
        ("halloween", "Halloween", "Spooky", ["halloween"]),
        ("valentine", "Valentine", "Romance", ["valentine"]),
        ("new_year", "New Year", "Holiday", ["new_year"]),
        ("summer", "Summer", "Warm season", ["summer"]),
        ("winter", "Winter", "Cold season", ["winter"]),
        ("spring", "Spring", "Season", ["spring"]),
        ("autumn", "Autumn", "Fall", ["autumn"]),
        ("monochrome", "Monochrome", "B&W art", ["monochrome"]),
        ("sepia", "Sepia", "Sepia tone", ["sepia"]),
        ("watercolor", "Watercolor", "Traditional", ["watercolor_(medium)"]),
        ("oil_painting", "Oil painting", "Traditional", ["oil_painting_(medium)"]),
        ("chibi_search", "Chibi", "Super-deformed", ["chibi"]),
        ("parody", "Parody", "Parody tag", ["parody"]),
        ("crossover", "Crossover", "Mixed series", ["crossover"]),
        ("meme", "Meme", "Meme art", ["meme"]),
        ("4koma", "4koma", "Comic strip", ["4koma"]),
        ("multiple_views", "Multiple views", "Angles", ["multiple_views"]),
        ("speech_bubble", "Speech bubble", "Dialogue", ["speech_bubble"]),
        ("english_text", "English text", "Text", ["english_text"]),
        ("japanese_text", "Japanese text", "Text", ["japanese_text"]),
        ("sound", "With sound", "Audio", ["sound"]),
        ("webm_search", "WebM", "WebM format", ["webm"]),
        ("absurdres", "Absurd resolution", "Very high res", ["absurdres"]),
        ("game_cg", "Game CG", "Visual novel", ["game_cg"]),
        ("visual_novel", "Visual novel", "VN art", ["visual_novel"]),
        ("official_art", "Official art", "Official", ["official_art"]),
        ("fanart", "Fan art", "Fanmade", ["fanart"]),
        ("cosplay_photo", "Cosplay photo", "Real cosplay", ["cosplay_photo"]),
        ("realistic_search", "Realistic", "Semi-real", ["realistic"]),
        ("photo_medium", "Photo", "Photograph", ["photo_(medium)"]),
        ("full_color", "Full color", "Colored", ["full_color"]),
        ("greyscale", "Greyscale", "Grayscale", ["greyscale"]),
        ("2girls", "Two girls", "Pair of girls", ["2girls"]),
        ("3girls", "Three girls", "Trio", ["3girls"]),
        ("4girls", "Four girls", "Quartet", ["4girls"]),
        ("1girl", "One girl", "Single girl", ["1girl"]),
        ("1boy", "One boy", "Single boy", ["1boy"]),
        ("2boys", "Two boys", "Pair of boys", ["2boys"]),
        ("mixed_bathing", "Mixed bathing", "Shared bath", ["mixed_bathing"]),
        ("bath", "Bath", "Bathtub", ["bath"]),
        ("hot_spring", "Hot spring", "Onsen scene", ["hot_spring"]),
        ("swimsuit", "Swimsuit", "Swimwear", ["swimsuit"]),
        ("one_piece_swimsuit", "One-piece swimsuit", "Swimwear", ["one-piece_swimsuit"]),
        ("bikini_top", "Bikini top only", "Partial swim", ["bikini_top_only"]),
        ("sideboob", "Sideboob", "Side exposure", ["sideboob"]),
        ("underboob", "Underboob", "Under exposure", ["underboob"]),
        ("cleavage", "Cleavage", "Chest line", ["cleavage"]),
        ("nipples", "Visible nipples", "Exposed", ["nipples"]),
        ("pussy", "Visible pussy", "Exposed", ["pussy"]),
        ("penis", "Visible penis", "Exposed", ["penis"]),
        ("spread_legs", "Spread legs", "Pose", ["spread_legs"]),
        ("ass", "Ass focus", "Rear", ["ass"]),
        ("ass_visible", "Ass visible", "Rear view", ["ass_visible_through_thighs"]),
        ("thigh_gap", "Thigh gap", "Legs", ["thigh_gap"]),
        ("pantyshot", "Pantyshot", "Upskirt", ["pantyshot"]),
        ("upskirt", "Upskirt", "Under skirt", ["upskirt"]),
        ("wardrobe_malfunction", "Wardrobe malfunction", "Accident", ["wardrobe_malfunction"]),
        ("see_through", "See-through", "Sheer clothes", ["see-through"]),
        ("wet_clothes", "Wet clothes", "Clinging fabric", ["wet_clothes"]),
        ("torn_clothes", "Torn clothes", "Ripped", ["torn_clothes"]),
        ("open_shirt", "Open shirt", "Unbuttoned", ["open_shirt"]),
        ("off_shoulder", "Off shoulder", "Bare shoulder", ["off_shoulder"]),
        ("bare_shoulders", "Bare shoulders", "Exposed shoulders", ["bare_shoulders"]),
        ("collarbone", "Collarbone", "Neckline", ["collarbone"]),
        ("midriff", "Midriff", "Belly", ["midriff"]),
        ("navel", "Navel", "Belly button", ["navel"]),
        ("back", "Back view", "From behind", ["back"]),
        ("from_behind", "From behind", "Rear angle", ["from_behind"]),
        ("from_above", "From above", "High angle", ["from_above"]),
        ("from_below", "From below", "Low angle", ["from_below"]),
        ("dutch_angle", "Dutch angle", "Tilted", ["dutch_angle"]),
        ("close_up", "Close-up", "Face focus", ["close-up"]),
        ("portrait", "Portrait", "Upper body", ["portrait"]),
        ("full_body", "Full body", "Whole figure", ["full_body"]),
        ("lying", "Lying down", "Reclined", ["lying"]),
        ("sitting", "Sitting", "Seated", ["sitting"]),
        ("standing", "Standing", "Upright", ["standing"]),
        ("kneeling", "Kneeling", "On knees", ["kneeling"]),
        ("on_bed", "On bed", "Bedroom", ["on_bed"]),
        ("bedroom", "Bedroom", "Indoor", ["bedroom"]),
        ("couch", "On couch", "Living room", ["couch"]),
        ("chair", "On chair", "Seated furniture", ["chair"]),
        ("table", "On table", "Furniture", ["table"]),
        ("window", "By window", "Natural light", ["window"]),
        ("cityscape", "Cityscape", "Urban", ["cityscape"]),
        ("sky", "Sky background", "Outdoors", ["sky"]),
        ("cloud", "Clouds", "Sky", ["cloud"]),
        ("sunset", "Sunset", "Golden hour", ["sunset"]),
        ("sunrise", "Sunrise", "Morning light", ["sunrise"]),
        ("star", "Starry sky", "Night sky", ["starry_sky"]),
        ("flower", "Flowers", "Floral", ["flower"]),
        ("rose", "Roses", "Romantic", ["rose"]),
        ("cherry_blossoms", "Cherry blossoms", "Sakura", ["cherry_blossoms"]),
        ("japanese_clothes", "Japanese clothes", "Traditional", ["japanese_clothes"]),
        ("chinese_clothes", "Chinese clothes", "Traditional", ["chinese_clothes"]),
        ("armor", "Armor", "Armored", ["armor"]),
        ("bodysuit", "Bodysuit", "Tight suit", ["bodysuit"]),
        ("leotard", "Leotard", "Dancewear", ["leotard"]),
        ("gym_uniform", "Gym uniform", "Sports", ["gym_uniform"]),
        ("track_suit", "Tracksuit", "Athletic", ["track_suit"]),
        ("sports_bra", "Sports bra", "Athletic", ["sports_bra"]),
        ("yoga_pants", "Yoga pants", "Athletic", ["yoga_pants"]),
        ("jeans", "Jeans", "Denim", ["jeans"]),
        ("shorts", "Shorts", "Short pants", ["shorts"]),
        ("miniskirt", "Miniskirt", "Short skirt", ["miniskirt"]),
        ("pleated_skirt", "Pleated skirt", "School style", ["pleated_skirt"]),
        ("sweater", "Sweater", "Knit top", ["sweater"]),
        ("hoodie", "Hoodie", "Casual", ["hoodie"]),
        ("jacket", "Jacket", "Outerwear", ["jacket"]),
        ("coat", "Coat", "Outerwear", ["coat"]),
        ("cape", "Cape", "Fantasy wear", ["cape"]),
        ("hat", "Hat", "Headwear", ["hat"]),
        ("beret", "Beret", "Headwear", ["beret"]),
        ("headphones", "Headphones", "Accessories", ["headphones"]),
        ("ribbon", "Ribbon", "Hair accessory", ["ribbon"]),
        ("hair_ornament", "Hair ornament", "Accessory", ["hair_ornament"]),
        ("hairband", "Hairband", "Accessory", ["hairband"]),
        ("earrings", "Earrings", "Jewelry", ["earrings"]),
        ("necklace", "Necklace", "Jewelry", ["necklace"]),
        ("choker", "Choker", "Neck accessory", ["choker"]),
        ("collar", "Collar", "Neck accessory", ["collar"]),
        ("gloves", "Gloves", "Hands", ["gloves"]),
        ("fingerless_gloves", "Fingerless gloves", "Hands", ["fingerless_gloves"]),
        ("stockings", "Stockings", "Legwear", ["stockings"]),
        ("pantyhose", "Pantyhose", "Legwear", ["pantyhose"]),
        ("fishnets", "Fishnets", "Legwear", ["fishnets"]),
        ("kneehighs", "Knee highs", "Socks", ["kneehighs"]),
        ("barefoot", "Barefoot", "No shoes", ["barefoot"]),
        ("shoes", "Shoes", "Footwear", ["shoes"]),
        ("boots", "Boots", "Footwear", ["boots"]),
        ("sandals", "Sandals", "Footwear", ["sandals"]),
        ("tail", "Tail", "Character tail", ["tail"]),
        ("horns", "Horns", "Demon etc", ["horns"]),
        ("wings", "Wings", "Angel/demon", ["wings"]),
        ("pointy_ears", "Pointy ears", "Elf etc", ["pointy_ears"]),
        ("fangs", "Fangs", "Vampire etc", ["fangs"]),
        ("heterochromia", "Heterochromia", "Different eye colors", ["heterochromia"]),
        ("red_eyes", "Red eyes", "Eye color", ["red_eyes"]),
        ("blue_eyes", "Blue eyes", "Eye color", ["blue_eyes"]),
        ("green_eyes", "Green eyes", "Eye color", ["green_eyes"]),
        ("purple_eyes", "Purple eyes", "Eye color", ["purple_eyes"]),
        ("yellow_eyes", "Yellow eyes", "Eye color", ["yellow_eyes"]),
        ("hetero_kiss", "Hetero kiss", "Couple kiss", ["1girl", "1boy", "kiss"]),
        ("yuri_kiss", "Yuri kiss", "Girls kissing", ["yuri", "2girls", "kiss"]),
        ("cuddling", "Cuddling", "Intimate", ["cuddling"]),
        ("hug", "Hug", "Embrace", ["hug"]),
        ("holding_hands", "Holding hands", "Romantic", ["holding_hands"]),
        ("lap_pillow", "Lap pillow", "Resting", ["lap_pillow"]),
        ("sleeping", "Sleeping", "Asleep", ["sleeping"]),
        ("waking_up", "Waking up", "Morning", ["waking_up"]),
        ("bathing", "Bathing", "Wash scene", ["bathing"]),
        ("towel", "Towel", "After bath", ["towel"]),
        ("soap", "Soap bubbles", "Bath", ["soap_bubbles"]),
        ("steam", "Steam", "Hot scene", ["steam"]),
        ("censored", "Censored", "Mosaic etc", ["censored"]),
        ("mosaic_censoring", "Mosaic", "Pixel censor", ["mosaic_censoring"]),
        ("bar_censor", "Bar censor", "Black bar", ["bar_censor"]),
        ("convenient_censoring", "Convenient censor", "Strategic cover", ["convenient_censoring"]),
        ("no_humans", "No humans", "Landscape/object", ["no_humans"]),
        ("multiple_girls", "Multiple girls", "Several girls", ["multiple_girls"]),
        ("solo_focus", "Solo focus", "One character focus", ["solo_focus"]),
        ("character_name", "Named character", "Has character tag", ["character_name"]),
    ]
    for row in acts:
        add_unique(presets, seen, *row)

    return presets


def build_blacklist() -> list:
    presets: list = []
    seen = set(BASE_BLACKLIST_IDS)

    topics = [
        ("guro_light", "Light guro", "Blood and injury", ["blood", "injury", "bruise", "wound"]),
        ("amputation", "Amputation", "Missing limbs", ["amputation", "stump", "missing_limb"]),
        ("asphyxiation", "Asphyxiation", "Choking/strangling", ["asphyxiation", "strangling", "choking"]),
        ("electrocution", "Electrocution", "Electric torture", ["electrocution", "electric_torture"]),
        ("fire_play", "Fire play", "Burns", ["fire", "burn", "burning"]),
        ("knife_play", "Knife play", "Blades", ["knife", "blade", "cutting"]),
        ("gunplay", "Gunplay", "Firearms in scene", ["gun", "firearm", "gunplay"]),
        ("snuff", "Snuff", "Death themes", ["snuff", "death", "dying"]),
        ("ryona", "Ryona", "Beat-up fetish", ["ryona", "beaten", "bruised"]),
        ("unbirth", "Unbirth", "Reverse birth", ["unbirth"]),
        ("cock_vore", "Cock vore", "Genital vore", ["cock_vore"]),
        ("anal_vore", "Anal vore", "Anal vore", ["anal_vore"]),
        ("soft_vore", "Soft vore", "Non-fatal vore", ["soft_vore"]),
        ("hard_vore", "Hard vore", "Fatal vore", ["hard_vore"]),
        ("oral_vore", "Oral vore", "Mouth vore", ["oral_vore"]),
        ("full_tour", "Full tour vore", "Digestion path", ["full_tour"]),
        ("digestion", "Digestion", "Stomach acids", ["digestion", "stomach_acids"]),
        ("weight_gain", "Weight gain", "Fattening", ["weight_gain", "fattening", "getting_fatter"]),
        ("feederism", "Feederism", "Feeding kink", ["feederism", "feeding"]),
        ("vore_alt", "Vore (extra tags)", "More vore tags", ["vore", "pred", "prey"]),
        ("macro", "Macro", "Giant size", ["macro", "giant", "giantess"]),
        ("micro", "Micro", "Tiny size", ["micro", "shrunken", "minigirl", "miniboy"]),
        ("size_difference", "Extreme size difference", "Huge gap", ["size_difference"]),
        ("unbirth_alt", "Unbirth alt", "More unbirth", ["unbirthing"]),
        ("furry_insects", "Furry insects", "Bug anthro", ["insect", "arthropod", "bug"]),
        ("furry_aquatic", "Furry aquatic", "Fish/sea anthro", ["aquatic", "fish", "shark", "dolphin"]),
        ("furry_plant", "Plant furry", "Plant anthro", ["plant", "plantification"]),
        ("furry_robot", "Robot furry", "Mecha anthro", ["robot", "mecha", "cyborg"]),
        ("feral", "Feral", "Non-anthro animals", ["feral", "feral_intercourse", "animal_genitalia"]),
        ("zoophilia_extra", "Zoophilia extra", "More bestiality tags", ["zoophilia", "animal_penetration"]),
        ("human_on_feral", "Human on feral", "Human/animal", ["human_on_feral"]),
        ("animal_on_human", "Animal on human", "Animal/human", ["animal_on_human"]),
        ("dog", "Dogs", "Canine content", ["dog", "canine", "puppy"]),
        ("horse", "Horses", "Equine content", ["horse", "equine"]),
        ("pig", "Pigs", "Swine content", ["pig", "swine"]),
        ("cow", "Cows", "Bovine content", ["cow", "bovine"]),
        ("sheep", "Sheep", "Ovine content", ["sheep", "ovine"]),
        ("reptile_furry", "Reptile furry", "Scales", ["reptile", "scalie", "snake", "lizard"]),
        ("avian_furry_extra", "Avian furry extra", "Birds", ["bird", "avian", "feathered_wings"]),
        ("prolapse", "Prolapse", "Medical extreme", ["prolapse"]),
        ("gaping", "Gaping", "Extreme stretch", ["gaping", "gaping_anus", "gaping_pussy"]),
        ("fisting", "Fisting", "Hand insertion", ["fisting", "anal_fisting", "vaginal_fisting"]),
        ("enema", "Enema", "Enema play", ["enema"]),
        ("enema_alt", "Enema alt", "Colon play", ["colon_play"]),
        ("scat_extra", "Scat extra", "More scat tags", ["scat", "feces", "defecation", "coprophagia"]),
        ("fart_extra", "Fart extra", "More gas tags", ["fart", "flatulence", "farting"]),
        ("burping", "Burping", "Belching", ["burp", "belching"]),
        ("vomit", "Vomit", "Emetophilia", ["vomit", "vomiting", "puke"]),
        ("spit", "Spit", "Spitting", ["spit", "spitting"]),
        ("saliva", "Saliva excess", "Drool focus", ["saliva", "drooling", "slobber"]),
        ("nosebleed", "Nosebleed", "Blood from nose", ["nosebleed"]),
        ("menstruation", "Menstruation", "Period", ["menstruation", "period"]),
        ("urination_extra", "Urination extra", "More pee tags", ["urination", "peeing", "pee", "golden_shower"]),
        ("diaper_extra", "Diaper extra", "More ABDL", ["diaper", "abdl", "adult_baby"]),
        ("age_regression", "Age regression", "Mental/physical age", ["age_regression", "age_play"]),
        ("dollification", "Dollification", "Doll TF", ["dollification", "doll"]),
        ("statue", "Statue TF", "Stone/frozen", ["statue", "petrification", "frozen"]),
        ("latex_extra", "Latex extra", "Rubber gear", ["latex", "rubber", "rubber_suit"]),
        ("vacbed", "Vacbed", "Vacuum bed", ["vacbed", "vacuum_bed"]),
        ("bondage_extra", "Bondage extra", "More restraint", ["shibari", "rope_bondage", "cuffs", "chains"]),
        ("gag", "Gags", "Mouth gags", ["gag", "ball_gag", "ring_gag"]),
        ("blindfold", "Blindfold", "Eyes covered", ["blindfold"]),
        ("chastity", "Chastity", "Locked genitals", ["chastity", "chastity_cage", "chastity_belt"]),
        ("cbt", "CBT", "Genital torture", ["cbt", "ball_busting", "testicle_torture"]),
        ("nipple_torture", "Nipple torture", "Pain play", ["nipple_torture", "nipple_clamps"]),
        ("wax_play", "Wax play", "Hot wax", ["wax_play", "candle_wax"]),
        ("needle_play", "Needle play", "Piercing pain", ["needle_play", "piercing_play"]),
        ("breath_play", "Breath play", "Breath control", ["breath_play"]),
        ("pet_play", "Pet play", "Petplay", ["pet_play", "petplay", "leash", "collar"]),
        ("pony_play", "Pony play", "Harness cart", ["pony_play"]),
        ("humiliation_extra", "Humiliation extra", "Degradation", ["degradation", "humiliation", "insult"]),
        ("public_humiliation", "Public humiliation", "Exposed shame", ["public_humiliation", "embarrassed_public"]),
        ("filming", "Filming", "Camera recording", ["filming", "camera", "recording"]),
        ("prostitution", "Prostitution", "Sex work", ["prostitution", "hooker"]),
        ("cheating", "Cheating", "Affair", ["cheating", "affair"]),
        ("netorare_extra", "NTR extra", "Cuckolding tags", ["netorare", "cuckolding", "cuckold"]),
        ("rape_extra", "Non-con extra", "More force tags", ["rape", "forced", "non-consensual"]),
        ("drugged", "Drugged", "Intoxicated sex", ["drugged", "intoxicated"]),
        ("hypnosis_extra", "Hypnosis extra", "Mind control tags", ["hypnosis", "hypnotized", "mind_break"]),
        ("brainwashing", "Brainwashing", "Conditioning", ["brainwashing", "conditioning"]),
        ("corruption", "Corruption", "Fallen hero", ["corruption", "corrupted"]),
        ("monster_girl_exclude", "Monster girl", "Monstergirls", ["monster_girl", "monstergirl"]),
        ("slime_girl", "Slime girl", "Slime characters", ["slime_girl"]),
        ("robot_girl", "Robot girl", "Android girls", ["robot_girl", "android"]),
        ("undead", "Undead", "Zombie/ghost", ["zombie", "ghost", "undead"]),
        ("necrophilia_extra", "Necrophilia extra", "Dead body", ["necrophilia", "corpse"]),
        ("parasite_extra", "Parasite extra", "Parasites", ["parasite", "parasitic", "infestation"]),
        ("insect_sex", "Insect sex", "Bug sex", ["insect_sex", "bee", "wasp", "spider"]),
        ("tentacle_extra", "Tentacle extra", "More tentacle", ["tentacle_sex", "tentacle_penetration"]),
        ("oviposition", "Oviposition", "Egg laying", ["oviposition", "egg_laying"]),
        ("egg_implant", "Egg implant", "Internal eggs", ["egg_implant"]),
        ("birth", "Birth", "Labor/birth", ["birth", "labor"]),
        ("impregnation", "Impregnation", "Bred", ["impregnation", "breeding"]),
        ("pregnant_extra", "Pregnant extra", "More pregnancy", ["pregnant", "pregnancy", "belly"]),
        ("lactation_extra", "Lactation extra", "Milk", ["lactation", "breast_milk", "milking"]),
        ("hyper_breasts", "Hyper breasts", "Extreme chest", ["hyper_breasts", "hyper_boobs"]),
        ("hyper_ass", "Hyper ass", "Extreme rear", ["hyper_ass", "hyper_butt"]),
        ("hyper_belly", "Hyper belly", "Extreme stomach", ["hyper_belly"]),
        ("hyper_muscles", "Hyper muscles", "Extreme muscle", ["hyper_muscles", "hyper_muscle"]),
        ("muscular_male_extra", "Muscular male extra", "Muscle men", ["muscular_male", "bodybuilder"]),
        ("obese", "Obese", "Very fat", ["obese", "fat", "morbidly_obese"]),
        ("skinny", "Extreme thin", "Very thin", ["skinny", "anorexic"]),
        ("ugly", "Ugly", "Unattractive focus", ["ugly", "unattractive"]),
        ("old", "Elderly", "Old characters", ["old", "elderly", "grandmother", "grandfather"]),
        ("baby", "Infants", "Babies", ["baby", "infant"]),
        ("toddler", "Toddlers", "Young children", ["toddler"]),
        ("child", "Children", "Child characters", ["child"]),
        ("young", "Young-looking", "Youth-coded", ["young", "young-looking"]),
        ("student_loli", "Schoolchild coded", "Young uniform", ["elementary_school_uniform"]),
        ("teacher_student", "Teacher/student", "Power imbalance", ["teacher_and_student"]),
        ("family", "Family taboo", "Relatives", ["family", "relative", "sister", "brother", "mother", "father"]),
        ("step_family", "Step-family", "Step relations", ["step-sister", "step-brother", "step-mother", "step-father"]),
        ("cousin", "Cousin", "Cousin incest", ["cousin"]),
        ("aunt_uncle", "Aunt/uncle", "Extended family", ["aunt", "uncle"]),
        ("twincest", "Twincest", "Twins", ["twincest", "twins"]),
        ("yuri_exclude_extra", "Yuri extra", "Girl-girl", ["yuri", "girls_only", "2girls", "tribadism"]),
        ("yaoi_extra", "Yaoi extra", "Boy-boy", ["yaoi", "males_only", "2boys"]),
        ("futa_extra", "Futa extra", "More futa tags", ["futanari", "futa", "dickgirl", "herm"]),
        ("male_focus_extra", "Male focus extra", "Male-centric", ["male_focus", "1boy"]),
        ("solo_male_exclude", "Solo male", "Male solo", ["solo_male", "1boy", "solo"]),
        ("solo_female_exclude", "Solo female only", "No solo female", ["solo_female"]),
        ("group_male", "Male group", "Multiple males", ["multiple_boys", "group_of_men"]),
        ("trans", "Trans themes", "Trans characters", ["transgender", "trans", "trans_woman", "trans_man"]),
        ("crossdressing", "Crossdressing", "Opposite gender clothes", ["crossdressing", "trap"]),
        ("sissy", "Sissy", "Feminization", ["sissy", "feminization"]),
        ("forced_feminization", "Forced feminization", "Forced dress", ["forced_feminization"]),
        ("gender_swap", "Gender swap", "TG", ["gender_swap", "gender_bender"]),
        ("mtf", "MTF", "Male to female", ["mtf"]),
        ("ftm", "FTM", "Female to male", ["ftm"]),
        ("herm_extra", "Herm extra", "Intersex", ["herm", "intersex"]),
        ("cuntboy", "Cuntboy", "Male with vagina", ["cuntboy"]),
        ("gynomorph", "Gynomorph", "Feminine male body", ["gynomorph"]),
        ("andromorph", "Andromorph", "Masculine female body", ["andromorph"]),
        ("ai_extra", "AI extra", "More AI tags", ["ai_generated", "stable_diffusion", "novelai", "midjourney"]),
        ("3d_exclude", "3D render", "CGI", ["3d", "3d_(artwork)", "render"]),
        ("western_cartoon", "Western cartoon", "Western style", ["western_cartoon", "western_animation"]),
        ("live_action", "Live action", "Real people", ["live_action", "real_person"]),
        ("photo_real", "Photoreal", "Photos", ["photo_(medium)", "photograph"]),
        ("low_quality", "Low quality", "Bad art", ["low_quality", "bad_anatomy", "bad_proportions"]),
        ("watermark", "Watermark", "Marked images", ["watermark", "sample_watermark"]),
        ("comic_exclude", "Comics", "Multi-page", ["comic", "comic_page"]),
        ("text_heavy", "Text heavy", "Lots of text", ["text_heavy", "speech_bubble"]),
        ("meme_exclude", "Memes", "Meme posts", ["meme"]),
        ("gore_extra", "Gore extra", "Graphic violence", ["gore", "guro", "dismemberment", "entrails"]),
        ("blood_extra", "Blood extra", "Blood focus", ["blood", "bloody"]),
        ("weapon", "Weapons", "Guns and blades", ["weapon", "sword", "gun"]),
        ("military_violence", "Military violence", "War themes", ["military", "war", "soldier"]),
        ("political", "Political", "Political themes", ["political", "nazi", "confederate"]),
        ("religious", "Religious", "Religious themes", ["religious", "crucifixion"]),
        ("racist", "Racist themes", "Hate imagery", ["racist", "racism"]),
        ("diaper_mess", "Diaper mess", "Soiled diaper", ["diaper_mess", "messy_diaper"]),
        ("toilet", "Toilet", "Bathroom filth", ["toilet", "bathroom"]),
        ("mucus", "Mucus", "Snot/slime bodily", ["mucus", "snot"]),
        ("ear_play", "Ear play", "Ear fetish", ["ear_play", "ear_fuck"]),
        ("navel_play", "Navel play", "Belly button", ["navel_fuck", "navel_play"]),
        ("armpit_extra", "Armpit extra", "More armpit", ["armpit", "armpit_hair", "armpit_licking"]),
        ("belly_button", "Belly", "Stomach focus", ["belly", "stomach"]),
        ("feet_extra", "Feet extra", "More foot tags", ["feet", "foot_focus", "toes", "soles", "footjob"]),
        ("tickling_extra", "Tickling extra", "More tickle", ["tickling", "tickle_torture"]),
        ("smoking_extra", "Smoking extra", "Tobacco", ["smoking", "cigarette", "cigar"]),
        ("alcohol", "Alcohol", "Drunk themes", ["alcohol", "drunk", "beer", "wine"]),
        ("drugs_extra", "Drugs extra", "Substances", ["drugs", "cocaine", "heroin", "meth"]),
        ("piercing_extreme", "Extreme piercing", "Heavy mods", ["piercing", "body_modification"]),
        ("tattoo_heavy", "Heavy tattoos", "Full ink", ["tattoo", "full_body_tattoo"]),
        ("scar", "Scars", "Scar focus", ["scar", "scarring"]),
        ("amputee_extra", "Amputee extra", "More amputee", ["amputee", "amputation"]),
        ("wheelchair", "Wheelchair", "Disability", ["wheelchair"]),
        ("blind", "Blind", "Vision disability", ["blind"]),
        ("deaf", "Deaf", "Hearing disability", ["deaf"]),
        ("paralysis", "Paralysis", "Immobilized", ["paralysis", "paralyzed"]),
        ("medical", "Medical play", "Hospital extreme", ["medical", "hospital", "syringe"]),
        ("surgery", "Surgery", "Operation", ["surgery", "operation"]),
        ("castration", "Castration", "Genital removal", ["castration"]),
        ("circumcision", "Circumcision", "Cutting theme", ["circumcision"]),
        ("circumcision_play", "Genital mod", "Body mod", ["genital_modification"]),
        ("urethral", "Urethral", "Sounding", ["urethral", "sounding"]),
        ("anal_prolapse", "Anal prolapse", "Rear prolapse", ["anal_prolapse"]),
        ("cervix", "Cervix", "Deep penetration", ["cervix", "cervix_penetration"]),
        ("x_ray", "X-ray view", "Internal view", ["x-ray"]),
        ("internal", "Internal view", "Cross-section", ["internal", "cross-section"]),
        ("stomach_bulge", "Stomach bulge", "Visible outline", ["stomach_bulge"]),
        ("inflation_extra", "Inflation extra", "More inflation", ["inflation", "inflated", "belly_inflation"]),
        ("cum_inflation", "Cum inflation", "Fluid swell", ["cum_inflation"]),
        ("breast_expansion", "Breast expansion", "Growing chest", ["breast_expansion"]),
        ("ass_expansion", "Ass expansion", "Growing rear", ["ass_expansion"]),
        ("muscle_growth", "Muscle growth", "Growing muscle", ["muscle_growth"]),
        ("shrinking", "Shrinking", "Size down", ["shrinking"]),
        ("growth", "Growth", "Size up", ["growth"]),
        ("transformation_extra", "TF extra", "More transformation", ["transformation", "tf", "morph"]),
        ("species_transformation", "Species TF", "Species change", ["species_transformation"]),
        ("gender_transformation", "Gender TF", "Sex change", ["gender_transformation"]),
        ("inanimate", "Inanimate TF", "Object TF", ["inanimate_transformation"]),
        ("food_tf", "Food TF", "Edible TF", ["food_transformation"]),
        ("clothing_tf", "Clothing TF", "Living clothes", ["living_clothes"]),
        ("possession", "Possession", "Body takeover", ["possession", "body_takeover"]),
        ("ghost", "Ghost", "Spectral", ["ghost"]),
        ("demon", "Demon", "Hell themes", ["demon", "hell"]),
        ("religion_dark", "Dark religion", "Occult extreme", ["occult", "satanic"]),
        ("public_nudity", "Public nudity", "Exhibitionism", ["public_nudity", "exhibitionism"]),
        ("voyeurism", "Voyeurism", "Watching", ["voyeurism", "peeping"]),
        ("hidden_sex", "Hidden sex", "Secret act", ["hidden_sex", "stealth_sex"]),
        ("prostitution_extra", "Prostitution extra", "Escort", ["escort", "brothel"]),
        ("slave_extra", "Slavery extra", "Ownership", ["slave", "slavery", "owned"]),
        ("branding", "Branding", "Marking slave", ["branding", "brand"]),
        ("piercing_slave", "Piercing slave", "Permanent mods", ["piercing_slave"]),
        ("chain", "Chains", "Restraint", ["chain", "chained"]),
        ("cage", "Cage", "Imprisonment", ["cage", "caged"]),
        ("dungeon", "Dungeon", "BDSM room", ["dungeon"]),
        ("whip", "Whipping", "Flagellation", ["whip", "whipping", "flogging"]),
        ("spanking", "Spanking", "Impact play", ["spanking"]),
        ("paddle", "Paddle", "Impact play", ["paddle"]),
        ("crop", "Riding crop", "Impact play", ["riding_crop"]),
        ("hot_wax", "Hot wax", "Wax torture", ["hot_wax"]),
        ("ice_play", "Ice play", "Temperature", ["ice_play"]),
        ("temperature", "Temperature play", "Hot/cold", ["temperature_play"]),
        ("suspension", "Suspension", "Hanging bondage", ["suspension"]),
        ("hogtie", "Hogtie", "Bound pose", ["hogtie"]),
        ("mummification", "Mummification", "Wrapped bound", ["mummification"]),
        ("encasement", "Encasement", "Trapped in material", ["encasement"]),
        ("vacuum", "Vacuum", "Suction play", ["vacuum"]),
        ("machine", "Sex machine", "Mechanical", ["sex_machine", "machine"]),
        ("robot_sex", "Robot sex", "Mechanical partner", ["robot_sex"]),
        ("doll", "Sex doll", "Doll partner", ["sex_doll"]),
        ("inflatable", "Inflatable toy", "Pool toy etc", ["inflatable"]),
        ("object_insertion", "Object insertion", "Non-toy insert", ["object_insertion"]),
        ("large_insertion", "Large insertion", "Oversized", ["large_insertion"]),
        ("anal_beads", "Anal beads", "Toy", ["anal_beads"]),
        ("butt_plug", "Butt plug", "Toy", ["butt_plug"]),
        ("strap_on", "Strap-on", "Pegging gear", ["strap-on"]),
        ("double_dildo", "Double dildo", "Toy", ["double_dildo"]),
        ("sybian", "Sybian", "Ride machine", ["sybian"]),
        ("vibrator_extra", "Vibrator extra", "More toy tags", ["vibrator", "egg_vibrator", "remote_vibrator"]),
        ("denial", "Orgasm denial", "Edging", ["orgasm_denial", "edging"]),
        ("forced_orgasm", "Forced orgasm", "Overstim", ["forced_orgasm"]),
        ("ruined_orgasm", "Ruined orgasm", "Denied finish", ["ruined_orgasm"]),
        ("chastity_play", "Chastity play", "Locked", ["chastity_play"]),
        ("cuckquean", "Cuckquean", "Female cuck", ["cuckquean"]),
        ("hotwife", "Hotwife", "Sharing wife", ["hotwife"]),
        ("swinging", "Swinging", "Partner swap", ["swinging"]),
        ("orgy", "Orgy", "Large group", ["orgy"]),
        ("gangbang_exclude", "Gangbang", "Many on one", ["gangbang"]),
        ("bukkake_exclude", "Bukkake", "Many finish", ["bukkake"]),
        ("cum_play", "Cum play", "Fluid play", ["cum_play", "cum_bath"]),
        ("saliva_swap", "Saliva swap", "Spit swap", ["saliva_swap"]),
        ("kiss_exclude", "Kissing", "Kiss scenes", ["kiss"]),
        ("romance_exclude", "Romance", "Soft romantic", ["romance", "romantic"]),
        ("vanilla_exclude", "Vanilla", "Soft sex", ["vanilla"]),
        ("rough_sex", "Rough sex", "Aggressive", ["rough_sex", "aggressive"]),
        ("praise", "Praise kink", "Positive dom", ["praise_kink"]),
        ("degradation_extra", "Degradation extra", "Name-calling", ["degradation", "name_calling"]),
        ("watersports_extra", "Watersports extra", "Urine play", ["watersports", "urine"]),
        ("scat_play", "Scat play", "Feces play", ["scat_play"]),
        ("filth", "Filth", "Dirty themes", ["filth", "dirty"]),
        ("trash", "Trashy", "Low class theme", ["trashy"]),
        ("homeless", "Homeless", "Street themes", ["homeless"]),
        ("poverty", "Poverty", "Poor themes", ["poverty"]),
        ("fat_shaming", "Fat shaming", "Body shame", ["fat_shaming"]),
        ("racism_play", "Race play", "Controversial", ["race_play"]),
        ("religious_play", "Religious play", "Sacrilege", ["religious_play"]),
    ]
    for row in topics:
        add_unique(presets, seen, *row)

    return presets


def main():
    search = build_search()
    blacklist = build_blacklist()
    write_file(ROOT / "SearchPresetCatalog.Extended.cs", "SearchPresetCatalog", "SearchPreset", search)
    write_file(ROOT / "BlacklistPresetCatalog.Extended.cs", "BlacklistPresetCatalog", "BlacklistPreset", blacklist)
    print(f"Search extended: {len(search)} presets")
    print(f"Blacklist extended: {len(blacklist)} presets")
    print(f"Search total (approx): {len(BASE_SEARCH_IDS) + len(search)}")
    print(f"Blacklist total (approx): {len(BASE_BLACKLIST_IDS) + len(blacklist)}")


if __name__ == "__main__":
    main()
